### ISSUE TITLE
Thank you for your plugin

### ISSUE THREAD

**Issue by Surile** [ifsnow/react-native-infinite-flatlist-patch#1]
I encountered the onEndReached repeated request in the company's project. I have not solved it in one day. I saw the plugin you wrote in the official issue. After downloading it, I found that it really solved my problem. Thank you very much.

**Comment by ifsnow** [comment]
@Surile I'm so happy that your problem is solved by mine :)

**Comment by Surile** [comment]
![image](https://user-images.githubusercontent.com/28652894/68759627-01c19880-064b-11ea-91e5-990732af666f.png)
@ifsnow i Have you ever encountered this kind of problem? I am getting this error when trying to package Android.

**Comment by ifsnow** [comment]
@Surile I'm sorry to say that I've never experienced the error. I hope you find a solution quickly.
